### ISSUE TITLE
Doc request: examples/guidelines for docstring format

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#103]
Python has many different standards for docstrings. In the shiny sources, our docs roughly follow numpydoc guidelines, but with some sphinx features (mostly using rst), like:
- `` :func:`~foo.bar` ``
-  `` `layout guide <https://shiny.rstudio.com/articles/layout-guide.html>`_ `` (Note that this 
- Double backticks around inline code

However, the resulting docstrings are a bit of a mess because some of the sphinx/rst features are handled well by quartodoc, but others are not. Also, some features seem to be handle OK in some sections of docstrings, but not others.

It would be very helpful if quartodoc recommended a format that is:
- Readable as plain text
- Can be cleanly converted to qmd

Additionally, it would be helpful to show many examples in the docs.

I _think_ that quartodoc wants the docstrings to have numpydoc-like structure (because that is how griffe parses out sections), with markdown formatting within that structure, but it is not entirely clear to me.

**Comment by machow** [comment]
Thanks for flagging -- I'll add a note that quartodoc expects numpydoc style syntax, and add notes around common gotchas (requiring the "s" on "Examples", "Examples" is the only section that supports code with `>>>`, etc..)

griffe has more parsers, but I don't think I can provide support around them anytime soon (since errors in writing a docstring take a lot of debugging, and many docstring styles would multiply that 😅).

**Comment by machow** [comment]
There's now a rough examples page

https://machow.github.io/quartodoc/get-started/docstring-examples.html
