### ISSUE TITLE
Table of contents arrow needs to rotate when open / closed

### ISSUE THREAD

**Issue by schloerke** [machow/quartodoc#134]
Currently there is no UI cues to tell me of a TOC menu is open.

#### Open
![Screenshot 2023-05-17 at 10 34 22 AM](https://github.com/machow/quartodoc/assets/93231/cff22816-4bcd-4ffe-825f-7c0964bc9d2b)

#### Closed
![Screenshot 2023-05-17 at 10 34 31 AM](https://github.com/machow/quartodoc/assets/93231/b8869f1e-dc88-40f5-b0a0-bd81c87e43f6)

-----------------------------

I'd expect when the drawer is open that the arrow points down (using `bi-chevron-down`)

![Screenshot 2023-05-17 at 10 38 36 AM](https://github.com/machow/quartodoc/assets/93231/d32fe3b9-1c0d-4761-949f-e35bb8bba3b9)

**Comment by machow** [comment]
Thanks for flagging, I wonder if is an issue with the quarto version we're using? Once we update, hopefully it should resolve 😬.

**Comment by machow** [comment]
Going to close, since it seems to have been resolved in later versions of quarto

<img width="727" alt="image" src="https://github.com/machow/quartodoc/assets/2574498/b7bed87d-8e1e-4714-b9fc-5b9107d342ce">

<img width="756" alt="image" src="https://github.com/machow/quartodoc/assets/2574498/79af0365-cff1-41eb-87aa-ba60b47dbae2">
