### ISSUE TITLE
Filtering attributes with `members` does not work as advertised

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#142]
The docs state that `members` can be used to filter attributes

<img width="544" alt="image" src="https://github.com/machow/quartodoc/assets/1483922/8126fac9-7084-4a9e-b1b2-f83b0fc54891">

But this is not the case.  values for the `members` field only seem to filter methods, and all attributes are shown.  In fact, I don't think there is a way to filter attributes in the config?

**Comment by machow** [comment]
It seems like there may be two forces at play here:

* If a class has an Attributes section of its docstring, then it gets rendered
* objects like classes and modules can also have individual attributes documented, similar to documenting methods.
  - in this case, `members` should let you filter what gets documented

I wonder what should happen in the case where an Attributes section exists AND `members` is specified? In any event, it makes sense that this behavior is confusing. I can take a quick look at how other tools handle this tomorrow....

**Comment by machow** [comment]
It looks like mkdocstrings (which is super great) just renders everything, if you have it:

* an Attributes section in your docstring
* individual attribute member docs (specified by the `members` option). 
  - these are automatically included if members is unspecified, and the attribute has a docstring

I can tee up work to do the same thing (so that metaflow.Current attributes will get automatically documented). I wonder if, once it's in place, that will reduce the confusion of trying to filter the Attributes section. I can see how documenting attributes 2 ways has the potential to create a lot of confusion.

## mkdocstring example

Here's a fairly involved example.

```python
class SomeClass:
    """Some cool class

    Parameters
    ----------
    c:
        woah man

    Attributes
    ----------
    a:
        The a attribute
    b:
        The b attribute
    """

    a: int
    b: int
    """Another thing."""


    def __init__(self, c: float):
        self.c = c
        """The c attribute"""

```

<img width="798" alt="image" src="https://github.com/machow/quartodoc/assets/2574498/b50d3fe9-bab8-489f-b393-f433e12d5f28">

**Comment by machow** [comment]
Let's track in this issue, which discusses more on rendering the attributes section, vs attributes individually:

* https://github.com/machow/quartodoc/issues/284
