### ISSUE TITLE
Turn off compound/expression interlinking by default

### ISSUE THREAD

**Issue by hamelsmu** [machow/quartodoc#167]
## Background

Compound types don't always interlink consistently because of the nuances of Python's typing system.  The failure modes on compound data type interlinking are confusing and distracting for the end user.  See examples below.

### Example 1 `spellcheck`

From [these shiny docs](https://shiny.rstudio.com/py/api/ui.input_text.html#parameters), see the last row in the below table, the compound type doesn't render consistently.

![image](https://github.com/machow/quartodoc/assets/1483922/d0549670-07db-46a2-9378-efec6e8ba6fd)

### Example 2: `object_name`

See the second row in the below table which will render as `str | None` because of the way this compound type is annotated in Griffe.

![image](https://github.com/machow/quartodoc/assets/1483922/4c59d3b1-8660-4ea2-a6af-e5cc27f0e82c)

#### Can we fix this?

We would have to make lots of upstream changes to Griffe, and it's not clear if this is desired in this situation.  More importantly its not clear that the effort is worth it, which is why we outlined the below three options

## Decision
There are three options:

1. Turn **interlinking off by default** completely (not even names)
2. Have two options: `names | all` 
   - `names`: would just render names like `MyType` and not compound types like `[List[Union[str, int], CustomType]` because this is brittle and has failure modes that can be confusing for end users when things don't interlink properly.  If you want a compound type to be rendered you would set the type equal to a variable like `MyType = [List[Union[str, int], CustomType]`
   - `all`: this is where we attempt to aggressively interlink everything, including compound types.
3. Only interlink named types and not compound types (Hamel's favorite).  This is the same as `#2` but doesn't allow for an option and just make this how quartodoc "works".  See "Hamel's Opinion" below for more explanation.

#### Hamel's Opinion:

I think we should render names only and not have any options.  If there are are compound types we should set them equal to a variable `MyType = [List[Union[str, int], CustomType]` and then that will render.  I think having too many options (`#2` above) is confusing!   I believe that if a compound type is "important" enough, that should either be a DataClass or assigned to a variable.

**Comment by hamelsmu** [comment]
cc: @isabelizimm @wch

**Comment by machow** [comment]
My 2 cents is toward two options: either 100% off or 100% on (attempt to render full expressions)

With it set off by default (at least for now), but toggleable in the config:

```yaml
quartodoc:
    renderer:
        crossrefs: true
```

In the case where `crossrefs: true` is set, the Builder would check the overall config to make sure a filter exists (e.g. `filters: ["interlinks"]` in `_quarto.yml`). I think later we could enforce things more strongly (e.g. the interlinks filter extension is always installed, and quartodoc has a project type that sets it in the config).

**Comment by isabelizimm** [comment]
My personal opinion is either 2 or 3 in Hamel's options.
I am anti 100% off because I personally find it valuable to have custom/unusual types linked. For partially vs. 100% linked, I have less strongly held opinions, but it's probably easier to explain to users that compound types are never linked, rather than saying it will be linked, but maybe sporadically/poorly.

**Comment by wch** [comment]
Is it not possible (or too difficult) to process the type annotations so that they can be properly interlinked? To me that would be the ideal solution.

In Shiny we use union types in many places, and if I'm understanding this issue correctly, then proposal 3 is to just not have links in those cases?

I think that the following isn't ideal (it should have more links, like to `Inputs`, `Outputs` and `Session`), but not having any links is strictly worse. 

<img width="785" alt="image" src="https://github.com/machow/quartodoc/assets/86978/f737e526-9d4d-4cef-b63d-39cdd0738ab0">


For the stuff we're doing, I don't think it makes sense to make a type specifically to stand in for those union types `MyUiType = Tag | TagList | Callable[[Request], Tag | TagList]`. We already create these types where we think it makes sense.

**Comment by has2k1** [comment]
> Is it not possible (or too difficult) to process the type annotations so that they can be properly interlinked? To me that would be the ideal solution.

I [did](
https://github.com/numpy/numpydoc/blob/3d4a5831f9f64246404a6dac5c5059a71b020952/numpydoc/xref.py) the processing and cross-referencing of annotations for `numpydoc` and I think the same processing could work here if it is happening in python.

**Comment by machow** [comment]
I checked generating some docs with mkdocstrings, and it seems like both cases are handled:

* postponed annotations using strings
* annotations that were imported from somewhere else (e.g. shiny.App imports `shiny.session.Inputs`, but documents `shiny.Inputs`)

So may just be a case of not using griffe to its fullest?

**Comment by hamelsmu** [comment]
Thanks for these comments.  It seems like interlinking annotations is indeed very important and desired (not just a "nice to have") thing.  

It sounds like it's worth it to spend time on this particular feature to smooth out all the sharp edges instead of trying to compromise.

**Comment by hamelsmu** [comment]
I'll go ahead and close this particular issue and we can reopen new ones as appropriate trying to tackle this.

**Comment by pawamoy** [comment]
Happy to help on the Griffe side :slightly_smiling_face:

**Comment by machow** [comment]
@pawamoy thanks for jumping in! I glanced a bit, and if I'm understanding correctly, mkdocstrings (and the autorefs) package resolves this by adding mappings for the canonical_path -> url for documented objects.

Something like...


* for expressions, the jinja [expressions.html template](https://github.com/mkdocstrings/python/blob/master/src/mkdocstrings_handlers/python/templates/material/_base/expression.html#L11) outputs <span data-autorefs-optional="..."> with the full expression name
* the mkdocs/autorefs package [extracts the expression name](https://github.com/mkdocstrings/autorefs/blob/4a45c3bbc08b6f403f25c513f6553109ae6ae5d2/src/mkdocs_autorefs/references.py#L207) from all these spans (AutorefsExtension wraps AutoRefInlineProcessor to do this)
* There is a AutoRefsPlugin that holds the mappings of item names to URLs. This [AutodocProcessor](https://github.com/mkdocstrings/mkdocstrings/blob/39de5db636bcc3ced12d0be3e6dc15d7b4997756/src/mkdocstrings/extension.py#L52) registers item -> url mappings (e.g. register_anchor).

Essentially, because AutodocProcessor registers the "canonical_name" (essentially the path to the source definition) -> url, it is able to link to a lot of things internally.

Does that sound right? I think I was able to resolve many of the interlinking challenges by doing a similar thing in this [PR](https://github.com/machow/quartodoc/pull/180)! (As usual griffe had all the pieces already! :).

**Comment by pawamoy** [comment]
I think you got it right :slightly_smiling_face: 
The data flow is a bit challenging between mkdocstrings, handlers and autorefs, but yeah, essentially handlers prepare cross-references in the HTML output, in spans, using attributes that autorefs understands. In a later MkDocs hook, autorefs finds and replaces these spans, mapping identifiers to URLs from inventories. If the identifier is not known to autorefs, it asks again every handler if they know it (aliases!). In the end, it links to the right object (the one that was rendered, the one that's considered public by the package maintainers), whether the canonical path or an alias path was used.
