### ISSUE TITLE
Which versions of Python are supported?

### ISSUE THREAD

**Issue by juliasilge** [machow/quartodoc#169]
Looks like this is included:

https://github.com/machow/quartodoc/blob/7082f255554720ef139278b2be0859ef8b2bb555/setup.cfg#LL13C5-L13C42

But then a couple of lines later it says `python_requires = >=3.9`

**Comment by machow** [comment]
I had to drop support for python 3.8, due to an issue with one of our tools that uses typing (pydantic or plum) :/. I think we could add it back in the future, though hopefully with [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) recently dropping 3.8 support, this will be less of an issue in a few months.

(Will remove the pypi tag)
