### ISSUE TITLE
Missing function link when using handwritten api file

### ISSUE THREAD

**Issue by schloerke** [machow/quartodoc#203]
Shiny has a `ui.tags.qmd` file that is programmatically created as it has many methods.

This causes the list of methods to **not** be quartodoc aware. 

Because it is not directly listed in `_quarto.yml`, Shiny can not find links to the tag methods.

I'd like to be able to say `` :func:`~tags.h5` `` or `` :func:`~htmltools.h5` `` which we currently do with `` :func:`~htmltools.TagList` ``

**Comment by machow** [comment]
Thanks for raising, 

> Because it is not directly listed in _quarto.yml, Shiny can not find links to the tag methods.

When I generate the docs, and open the inventory file (`objects.json`) in the py-shiny docs repo, I see entries for shiny.ui.tags members. For example:

```
# an entry in objects.json
{"name": "shiny.ui.tags.a", "domain": "py", "role": "function", "priority": "1", "uri": "api/ui.tags.html#shiny.ui.tags.a", "dispname": "-"}

# another entry
{"name": "htmltools.tags.a", "domain": "py", "role": "function", "priority": "1", "uri": "api/ui.tags.html#shiny.ui.tags.a", "dispname": "shiny.ui.tags.a"}
```

Does linking to `` :func:`shiny.ui.tags.a` `` or `` :func:`htmltools.tags.a` `` work?

**Why not `htmltools.h5`?**

Because you documented it as `shiny.ui.tags.h5`, quartodoc created two inventory entries:

* one for the exact name used in `_quarto.yml` (`shiny.ui.tags.h5`)
* one for the canonical path to the function ([`htmltools.tags.h5`](https://github.com/rstudio/py-htmltools/blob/main/htmltools/tags.py#L510))

**Comment by schloerke** [comment]
Using ``:func:`~shiny.ui.tags.h5` `` works as expected!

Closing for now. I have some fuzziness about linking but can't describe it yet. Will re-open then.

**Comment by machow** [comment]
I wonder if this piece will end up making things easier?:

https://github.com/machow/quartodoc/issues/69

Basically, sphinx API docs set an option on doc pages, which lets you refer to things relative to a "current module". So...

* inside the docs for `shiny.ui.tags.h5`
* it would set the current module to `shiny.ui.tags`
* references like `` :func`:h5: `` could resolve relative to that module (`shiny.ui.tags.h5`)

**Comment by schloerke** [comment]
That would be nice!

---------------------

But I'd like to have the ability to refer to a function at **all** similar locations. 

Ex:
* ``:class:`shiny.Session` `` is the same class as ``:class:`shiny.session.Session` ``
* ``:func:`shiny.ui.tags.h5` `` is the same function as 
	* ``:func:`shiny.ui.h5` ``
	* ``:func:`htmltools.tags.h5` ``
	* ``:func:`htmltools.h5` ``

I'd be ok with `interlinks` changing the link location and link name to be a consistent value. When writing the docs is MUCH easier to link to an object / function given the location that it is being imported from.

**Comment by machow** [comment]
It wonder if it might be confusing to package users, to see the same function with many different paths?

Is there a recommended path to use when importing something like h5? I think the challenge right now in the shiny docs is there's no documentation for `shiny.ui.h5`, so it might be useful to either:

1. document everything on `shiny.ui` directly on the reference page (e.g. tags as their own section, which mentions you can also import `shiny.ui.tags` to see only tags)
2. OR, document `shiny.ui.tags` (and can always mention that these are also available on `shiny.ui`).

I could see the value of the current approach (2) in not wanting to documenting everything on `shiny.ui`, since it's pretty loaded. The separation into `tags` seems pretty useful, given the number of tags!

**Comment by machow** [comment]
Ah, I should say, focusing on

> I'd be ok with interlinks changing the link location and link name to be a consistent value. When writing the docs is MUCH easier to link to an object / function given the location that it is being imported from.

I can see how this piece fixes the experience I mentioned above for users. I think it might end up being a bit too much work in quartodoc / create a bit too much interlinks surface area 😓
