### ISSUE TITLE
Omit `self` in constructors and other method signatures

### ISSUE THREAD

**Issue by jcrist** [machow/quartodoc#270]
Currently `self` is included when rendering both constructor (`__init__`) and standard method signatures. It'd be nice if this parameter was omitted, as is done by other documentation tools like `sphinx`.

Examples from the `quartodoc` docs:

**Inclusion of `self` in `__init__`**

See [`quartodoc.MdRenderer`](https://machow.github.io/quartodoc/api/MdRenderer.html#quartodoc.MdRenderer)

> `MdRenderer(self, header_level=1, show_signature=True, show_signature_annotations=False, display_name='relative', hook_pre=None, render_interlinks=False)`

**Inclusion of `self` in other methods**

See [`quartodoc.MdRenderer.render_annotation`](https://machow.github.io/quartodoc/api/MdRenderer.render_annotation.html#quartodoc.MdRenderer.render_annotation)

> `MdRenderer.render_annotation(self, el)`

**Comment by machow** [comment]
Thanks for raising--I can take a quick stab at this! 

It looks like..

* sphinx [just checks `inspect.ismethod()`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/util/inspect.py#L580), and uses that to drop the first parameter
* mkdocstrings looks for parameters named ["self" or "cls" inside functions on classes](https://github.com/mkdocstrings/python/blob/2acf6f20d0e0e17f16c687d80e5c913922287359/src/mkdocstrings_handlers/python/templates/material/_base/signature.html#L20)

We'll likely need to follow mkdocstrings lead here, since we're also using griffe for static analysis

**Comment by machow** [comment]
Should be addressed in at least v0.6.3
