### ISSUE TITLE
Change interlinks specification.

### ISSUE THREAD

**Issue by has2k1** [machow/quartodoc#315]
The current way interlinks are specified is adapted directly from the [Intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) extension. This format uses [reStructuredText Interpreted Text Role](https://docutils.sourceforge.io/docs/ref/rst/roles.html) where, the colons and the backticks matter because the combination triggers the processing.

quartodoc implements interlinks using pandoc filters and the processing is triggered on markdown links where what matters is:

1. The link-target matches our spec
2. We can process the tokens in the target from right to left

So we do not need the combination of colons and backticks. We can do with only colons. Here is a comparison

|     | Intersphinx                                     | Current Interlink                                   | Proposed Interlink                             |
| --- | ----------------------------------------------- | --------------------------------------------------- | ---------------------------------------------- |
|  1  |                                                 | `` [](`target`) ``                                  | `[](:target:)`                                 |
|  2  | `` :reftype:`target` ``                         | `` [](:reftype:`target`) ``                         | `[](:reftype:target:)`                         |
|  3  | `` :domain:reftype:`target` ``                  | `` [](:domain:reftype:`target`) ``                  | `[](:domain:reftype:target:)`                  |
|  4  | `` :external:domain:reftype:`target` ``         | `` [](:external:domain:reftype:`target`) ``         | `[](:external:domain:reftype:target:)`         |
|  5  | `` :external+invname:domain:reftype:`target` `` | `` [](:external+invname:domain:reftype:`target`) `` | `[](:external+invname:domain:reftype:target:)` |
|  6  | `` :domain:reftype:`text<target>` ``            | `` [text](:domain:reftype:`target`) ``              | `[text](:domain:reftype:target:)`              |

Given the differences in processing Intersphinx format cannot (usually) represent only a target (case 1). And the translation rule to copy the Intersphinx stuff into the braces of a markdown link does not apply to all cases. We have a more natural solution for case 6.

While at best this saves us a single character, backticks are also a markdown syntax element and the proposed change invites less visual scrutiny and looks better without them.

This change can be implemented without affecting the current users. The current style may be dropped silently at first then deprecated with a warning.

**Comment by has2k1** [comment]
> The link syntax I most often think about is ``[some name](`some.target`)``.

The backticks are okay if you think of them that way (this is code to be processed).

But that does not cover all the cases. We have these too:

```md
[some name](:class:`some.target`)
[some name](:func:`some.target`)
[some name](:label:`some-ref`)
[some name](:py:label:`some-ref`)
```

which are RST roles. So we have inherited a syntax in an environment were some of its features are not required. The backticks no-longer mark all the code that will be processed and we are left with quirky thing with colons and backticks.

We can move the "sometimes" middle backtick to the beginning. This rescues the consistency of "this is a code to be processed".

```md
[some name](`some.target`)
[some name](`:class:some.target`)
[some name](`:func:some.target`)
[some name](`:ref:some-ref`)
[some name](`:py:ref:some-ref`)
```

Also, noting that most interlinks do not change the link text, most of the time we would endup with.

```md
[](`some.target`)
[](`:class:some.target`)
[](`:func:some.target`)
[](`:ref:some-ref`)
[](`:py:ref:some-ref`)
```

And when the `reftype` is specified we can use shorter form (with only quotes).

```md
[](`some.target`)
`:class:some.target`
`:func:some.target`
`:ref:some-ref`
`:py:ref:some-ref`
```

The full syntax that uses links would remain valid.

**Comment by machow** [comment]
> But that does not cover all the cases. We have these too:

> So we have inherited a syntax in an environment were some of its features are not required. The backticks no-longer mark all the code that will be processed and we are left with quirky thing with colons and backticks.

In my mind, the colons are a filtering syntax, which hopefully is not too commonly used (except in some standard library ambiguity cases). If I understand the original post, it sounds like the appeal to using all colons is consistency (since every part of the interlink would use the same separator `:`). Does that sound right?

**Comment by gadenbuie** [comment]
It'd be super nice if you only had to use brackets and parens when you need to change the link name, so it'd be awesome to have a short form for `` [](`target`) ``. Maybe `` `:target` ``?

**Comment by machow** [comment]
@gadenbuie agreed -- I think the trickiest thing here is figuring out something that is unambiguously an interlink in the pandoc AST.

For example, I think my original hope was that :py:`target` might resolve to something simple, but it becomes:

```
# quarto render test.qmd --to native --output --

[ Para [ Str ":py:" , Code ( "" , [] , [] ) "target" ] ]
```

I could see how @has2k1's  proposed above shortform `` `:reftype:target` `` might help, since its AST is...

```
[ Para [ Code ( "" , [] , [] ) ":reftype:target" ] ]
```

Which would be pretty easy to identify from a filter. Would be nice if there were some easier way to add classes, etc.. to inline code elements.

AFAIK the way to get classes on inline elements is to do things like `` `target`{.py} ``, which produces:

```
[ Para [ Code ( "" , [ "py" ] , [] ) "target" ] ]
```

**Comment by has2k1** [comment]
>  so it'd be awesome to have a short form for [](`target`). Maybe `:target`?

Yes. That can work. I have included it.

**Comment by machow** [comment]
I'm not too concerned about consistency, or removing the backtick in its own right. I'm going to close for now, and open an issue to focus exclusively on allowing an interlinks short-hand (e.g. using `` `:target` `` rather than the cumbersome [](`target`)).

Changes to the interlinks syntax seem fair game if they (1) enable a easy short-hand and (2) don't risk conflicting quarto rendering.

Thanks for digging into this topic so deeply. It's super helpful context for thinking about short-hand options!
