### ISSUE TITLE
shiny tag docstrings are rendering html

### ISSUE THREAD

**Issue by machow** [machow/quartodoc#67]
e.g. the description of `ui.tags.b` is rendering the `<b>`

![image](https://user-images.githubusercontent.com/2574498/225711339-ce9e639f-9711-4215-8eae-9c6529aeb318.png)

**Comment by machow** [comment]
@wch WDYT of having people responsible for escaping html in their docstrings? I noticed that mkdocstrings also renders the HTML. I think the challenge is that people can use markdown (e.g. for links), so HTML might be fair game in docstrings?....

<img width="768" alt="image" src="https://user-images.githubusercontent.com/2574498/225750382-c8569654-378b-4d33-ac91-88980c415397.png">

**Comment by wch** [comment]
Hm, I think that by default, quartodoc should escape the entire docstring, so that it looks like this:

\<b>

It would be up to the user to use backticks to indicate it's code, like if they want it to look like this:

`<b>`

The reason I say this is that there could be all sorts of characters that need escaping in HTML. For example, if I have some mathematical inequalities in the docstring, like "x<y and y>z", then if that less-than and greater-than symbols are not escaped, it will lead to some messed up HTML.

**Comment by machow** [comment]
I just overloaded the render and summarize methods in the shiny render, so it uses the python built-in `html.escape`, and it looks okay!

![image](https://user-images.githubusercontent.com/2574498/225764303-3c7d4ab5-bc0f-46a5-8b9d-28173dd930c7.png)
